#!/usr/bin/env node
// Keeps the Private Playtest Agreement's version and hash in one place.
//
//   node scripts/agreement.mjs sync   regenerate the ledger and the generated module
//   node scripts/agreement.mjs check  fail if anything is stale or a published version changed
//
// The source of truth is legal/<file>.md (front matter + text) and legal/current.json.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const legalDir = join(root, "legal");
const ledgerPath = join(legalDir, "agreement-ledger.json");
const generatedPath = join(root, "supabase/functions/_shared/agreement.generated.ts");

const VERSION_PATTERN = /^HEXENBANE-PLAYTEST-\d{4}-\d{2}-v\d+$/;

/** Canonical form: LF line endings, no trailing whitespace at the end, one final newline. */
export function canonicalize(text) {
  return text.replace(/\r\n?/g, "\n").replace(/\s+$/, "") + "\n";
}

export function sha256Hex(text) {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

export function parseAgreement(raw, fileName) {
  const text = raw.replace(/\r\n?/g, "\n").replace(/^﻿/, "");
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`${fileName}: missing front matter (--- version: ... ---)`);
  const meta = {};
  for (const line of match[1].split("\n")) {
    const kv = /^(\w+):\s*(.+)$/.exec(line.trim());
    if (kv) meta[kv[1]] = kv[2].trim();
  }
  if (!meta.version || !VERSION_PATTERN.test(meta.version)) {
    throw new Error(`${fileName}: front matter "version" must look like HEXENBANE-PLAYTEST-2026-10-v1`);
  }
  if (!meta.effective || !/^\d{4}-\d{2}-\d{2}$/.test(meta.effective)) {
    throw new Error(`${fileName}: front matter "effective" must be a YYYY-MM-DD date`);
  }
  const body = canonicalize(match[2].replace(/^\n+/, ""));
  return { file: fileName, version: meta.version, effective: meta.effective, body, sha256: sha256Hex(body) };
}

function loadAll() {
  const files = readdirSync(legalDir).filter((f) => /^playtest-agreement-.+\.md$/.test(f)).sort();
  const agreements = files.map((f) => parseAgreement(readFileSync(join(legalDir, f), "utf8"), f));
  const seen = new Map();
  for (const a of agreements) {
    if (seen.has(a.version)) throw new Error(`${a.file} and ${seen.get(a.version)} both claim ${a.version}`);
    seen.set(a.version, a.file);
  }
  const { current } = JSON.parse(readFileSync(join(legalDir, "current.json"), "utf8"));
  const currentAgreement = agreements.find((a) => a.file === current);
  if (!currentAgreement) throw new Error(`legal/current.json points at ${current}, which does not exist`);
  return { agreements, current: currentAgreement };
}

function readLedger() {
  return existsSync(ledgerPath) ? JSON.parse(readFileSync(ledgerPath, "utf8")) : { versions: [] };
}

/** Published versions may be added to, never changed or removed. */
function ledgerProblems(ledger, agreements) {
  const problems = [];
  for (const entry of ledger.versions) {
    const now = agreements.find((a) => a.version === entry.version);
    if (!now) problems.push(`${entry.version} is in the ledger but its file (${entry.file}) is gone. Restore it: published agreements are permanent.`);
    else if (now.sha256 !== entry.sha256) {
      problems.push(
        `${entry.version} text changed (ledger ${entry.sha256.slice(0, 12)}…, file ${now.sha256.slice(0, 12)}…). ` +
          `Undo the edit and publish the change as a new version instead.`,
      );
    }
  }
  return problems;
}

function buildLedger(ledger, agreements) {
  const versions = [...ledger.versions];
  for (const a of agreements) {
    if (!versions.some((v) => v.version === a.version)) {
      versions.push({ version: a.version, file: a.file, effective: a.effective, sha256: a.sha256 });
    }
  }
  return {
    $comment: "Generated by scripts/agreement.mjs. Every agreement version ever published, with its SHA-256. Never hand-edit or remove entries.",
    versions,
  };
}

function buildModule(current) {
  return `// GENERATED by scripts/agreement.mjs from legal/${current.file}. Do not edit.
// To change the agreement, add a new legal/playtest-agreement-vN.md, point legal/current.json at it,
// and run \`npm run agreement:sync\`.
//
// The Edge Function records AGREEMENT_VERSION and AGREEMENT_SHA256 with every application;
// the website imports the same constants to display the text.

export const AGREEMENT_VERSION = ${JSON.stringify(current.version)};
export const AGREEMENT_EFFECTIVE_DATE = ${JSON.stringify(current.effective)};
/** SHA-256 (hex) of AGREEMENT_TEXT encoded as UTF-8. */
export const AGREEMENT_SHA256 = ${JSON.stringify(current.sha256)};
export const AGREEMENT_TEXT = ${JSON.stringify(current.body)};
`;
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main(process.argv[2]);

function main(mode) {
try {
  const { agreements, current } = loadAll();
  const ledger = readLedger();
  const problems = ledgerProblems(ledger, agreements);
  if (problems.length) {
    for (const p of problems) console.error(`✖ ${p}`);
    process.exit(1);
  }
  const nextLedger = JSON.stringify(buildLedger(ledger, agreements), null, 2) + "\n";
  const nextModule = buildModule(current);

  if (mode === "sync") {
    writeFileSync(ledgerPath, nextLedger);
    writeFileSync(generatedPath, nextModule);
    console.log(`✔ Current agreement: ${current.version}`);
    console.log(`  sha256 ${current.sha256}`);
    console.log(`  wrote legal/agreement-ledger.json and supabase/functions/_shared/agreement.generated.ts`);
  } else if (mode === "check") {
    const stale = [];
    if (!existsSync(ledgerPath) || readFileSync(ledgerPath, "utf8") !== nextLedger) stale.push("legal/agreement-ledger.json");
    if (!existsSync(generatedPath) || readFileSync(generatedPath, "utf8").replace(/\r\n/g, "\n") !== nextModule) {
      stale.push("supabase/functions/_shared/agreement.generated.ts");
    }
    if (stale.length) {
      console.error(`✖ Out of date: ${stale.join(", ")}. Run: npm run agreement:sync`);
      process.exit(1);
    }
    console.log(`✔ Agreement ${current.version} is in sync (sha256 ${current.sha256.slice(0, 16)}…)`);
  } else {
    console.error("Usage: node scripts/agreement.mjs <sync|check>");
    process.exit(2);
  }
} catch (err) {
  console.error(`✖ ${err.message}`);
  process.exit(1);
}
}
